### ISSUE TITLE
Assertion failure in checker/src/call_visitor.rs:2038

### ISSUE THREAD

**Issue by mbuesch** [endorlabs/MIRAI#26]
I tried latest MIRAI f08968e093e254c7059c856bc7a30659f9b4708c on a couple of my projects with this command:

```
cargo +nightly-2024-12-26 mirai
```

It always fails with this assertion error:

```
thread 'rustc' panicked at checker/src/call_visitor.rs:2038:9:
assertion failed: self.actual_args.len() == 3
stack backtrace:
   0:     0x7f5c793257e5 - std::backtrace::Backtrace::create::hf1e6a2c1e9418088
   1:     0x7f5c778a5bf5 - std::backtrace::Backtrace::force_capture::h86672cf8f1c851b1
   2:     0x7f5c76a2924e - std[a201ef36b49d18f0]::panicking::update_hook::<alloc[56ff70b42ea61b42]::boxed::Box<rustc_driver_impl[f3ea397c7a603cd9]::install_ice_hook::{closure#0}>>::{closure#0}
   3:     0x7f5c778bdb68 - std::panicking::rust_panic_with_hook::h10f7071601bc38c8
   4:     0x7f5c778bd826 - std::panicking::begin_panic_handler::{{closure}}::hac06dbea0f2067d4
   5:     0x7f5c778bb4b9 - std::sys::backtrace::__rust_end_short_backtrace::h00bdac232870ef2e
   6:     0x7f5c778bd51d - rust_begin_unwind
   7:     0x7f5c7459ae10 - core::panicking::panic_fmt::h4061f9d146b21c29
   8:     0x7f5c7507c2dc - core::panicking::panic::h232112d07f51fd61
   9:     0x5619cbf4f14c - mirai::call_visitor::CallVisitor::handle_copy_non_overlapping::h7e6688e8c966e517
                               at .../MIRAI/checker/src/call_visitor.rs:2038:9
  10:     0x5619cbf4f14c - mirai::call_visitor::CallVisitor::handled_as_special_function_call::h2827a822efc6c0e4
                               at .../MIRAI/checker/src/call_visitor.rs:603:17
  11:     0x5619cbee05a1 - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:743:12
  12:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  13:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  14:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  15:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
  16:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  17:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  18:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  19:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
  20:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  21:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  22:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  23:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
  24:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  25:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  26:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  27:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
  28:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  29:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  30:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  31:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
  32:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  33:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  34:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  35:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
  36:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  37:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  38:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  39:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
  40:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  41:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  42:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  43:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
  44:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  45:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  46:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  47:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
  48:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  49:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  50:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  51:     0x5619cbf4df94 - mirai::call_visitor::CallVisitor::inline_indirectly_called_function::h7c692a703f92b2e1
                               at .../MIRAI/checker/src/call_visitor.rs:1376:27
  52:     0x5619cbf4df94 - mirai::call_visitor::CallVisitor::handled_as_special_function_call::h2827a822efc6c0e4
                               at .../MIRAI/checker/src/call_visitor.rs:484:17
  53:     0x5619cbee05a1 - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:743:12
  54:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  55:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  56:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  57:     0x5619cbf41a0c - mirai::fixed_point_visitor::FixedPointVisitor::visit_loop_body::h51cbe07990185365
  58:     0x5619cbf41a0c - mirai::fixed_point_visitor::FixedPointVisitor::compute_fixed_point::h2ff1d56d65c2894d
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:151:26
  59:     0x5619cbf3f50a - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:85:21
  60:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  61:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  62:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  63:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
  64:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  65:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  66:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  67:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
  68:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  69:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  70:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  71:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
  72:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  73:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  74:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  75:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
  76:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  77:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  78:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  79:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
  80:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  81:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  82:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  83:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
  84:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  85:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  86:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  87:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
  88:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  89:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  90:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  91:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
  92:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
  93:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
  94:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
  95:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
  96:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
  97:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
  98:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
  99:     0x5619cbf41a0c - mirai::fixed_point_visitor::FixedPointVisitor::visit_loop_body::h51cbe07990185365
 100:     0x5619cbf41a0c - mirai::fixed_point_visitor::FixedPointVisitor::compute_fixed_point::h2ff1d56d65c2894d
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:151:26
 101:     0x5619cbf3f50a - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:85:21
 102:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
 103:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
 104:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
 105:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
 106:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
 107:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
 108:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
 109:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
 110:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
 111:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
 112:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
 113:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
 114:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
 115:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
 116:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
 117:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
 118:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
 119:     0x5619cbf479b1 - mirai::call_visitor::CallVisitor::create_and_cache_function_summary::hf9a7431b434d256f
                               at .../MIRAI/checker/src/call_visitor.rs:142:31
 120:     0x5619cbf48d1e - mirai::call_visitor::CallVisitor::get_function_summary::h11f5c96025461084
                               at .../MIRAI/checker/src/call_visitor.rs:377:35
 121:     0x5619cbee05da - mirai::block_visitor::BlockVisitor::visit_call::h99aab7918ef300d5
                               at .../MIRAI/checker/src/block_visitor.rs:746:32
 122:     0x5619cbedd39b - mirai::block_visitor::BlockVisitor::visit_terminator::h418104073f57b664
 123:     0x5619cbedc24a - mirai::block_visitor::BlockVisitor::visit_basic_block::hdf23a905b1dfd654
                               at .../MIRAI/checker/src/block_visitor.rs:106:13
 124:     0x5619cbf40ce6 - mirai::fixed_point_visitor::FixedPointVisitor::visit_basic_block::he8e7d83fefff5743
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:131:9
 125:     0x5619cbf3f6dc - mirai::fixed_point_visitor::FixedPointVisitor::visit_blocks::h72877af57cf5833b
                               at .../MIRAI/checker/src/fixed_point_visitor.rs:83:21
 126:     0x5619cbf19c5a - mirai::body_visitor::BodyVisitor::visit_body::h138b1fd6ac2a400b
                               at .../MIRAI/checker/src/body_visitor.rs:216:9
 127:     0x5619cbe57d8d - mirai::crate_visitor::CrateVisitor::analyze_body::{{closure}}::h8119d70c5dcf2fdf
                               at .../MIRAI/checker/src/crate_visitor.rs:184:23
 128:     0x5619cbe57d8d - mirai::crate_visitor::CrateVisitor::analyze_body::h0ee544043c817f8f
                               at .../MIRAI/checker/src/crate_visitor.rs:172:5
 129:     0x5619cbe57d8d - mirai::crate_visitor::CrateVisitor::analyze_some_bodies::{{closure}}::h8f42332216c74581
                               at .../MIRAI/checker/src/crate_visitor.rs:126:13
 130:     0x5619cbe57d8d - mirai::crate_visitor::CrateVisitor::analyze_some_bodies::h1e7def280d021468
                               at .../MIRAI/checker/src/crate_visitor.rs:70:5
 131:     0x5619cbe56be9 - mirai::callbacks::MiraiCallbacks::analyze_with_mirai::{{closure}}::h34bec87a7650f60f
                               at .../MIRAI/checker/src/callbacks.rs:174:9
 132:     0x5619cbe56be9 - mirai::callbacks::MiraiCallbacks::analyze_with_mirai::hc96b7f564dbc8582
                               at .../MIRAI/checker/src/callbacks.rs:130:5
 133:     0x5619cbe56be9 - <mirai::callbacks::MiraiCallbacks as rustc_driver_impl::Callbacks>::after_analysis::{{closure}}::h20986a363d545aba
                               at .../MIRAI/checker/src/callbacks.rs:117:9
 134:     0x5619cbe56be9 - <mirai::callbacks::MiraiCallbacks as rustc_driver_impl::Callbacks>::after_analysis::hacb4886bf3509d23
                               at .../MIRAI/checker/src/callbacks.rs:101:5
 135:     0x7f5c7904596b - rustc_interface[ce25af41c070b27f]::passes::create_and_enter_global_ctxt::<core[4c3d2792fb1360fb]::option::Option<rustc_interface[ce25af41c070b27f]::queries::Linker>, rustc_driver_impl[f3ea397c7a603cd9]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
 136:     0x7f5c78fb8364 - rustc_interface[ce25af41c070b27f]::interface::run_compiler::<(), rustc_driver_impl[f3ea397c7a603cd9]::run_compiler::{closure#0}>::{closure#1}
 137:     0x7f5c78ebce47 - std[a201ef36b49d18f0]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ce25af41c070b27f]::util::run_in_thread_with_globals<rustc_interface[ce25af41c070b27f]::util::run_in_thread_pool_with_globals<rustc_interface[ce25af41c070b27f]::interface::run_compiler<(), rustc_driver_impl[f3ea397c7a603cd9]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
 138:     0x7f5c78ebd2dc - <<std[a201ef36b49d18f0]::thread::Builder>::spawn_unchecked_<rustc_interface[ce25af41c070b27f]::util::run_in_thread_with_globals<rustc_interface[ce25af41c070b27f]::util::run_in_thread_pool_with_globals<rustc_interface[ce25af41c070b27f]::interface::run_compiler<(), rustc_driver_impl[f3ea397c7a603cd9]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[4c3d2792fb1360fb]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
 139:     0x7f5c78ebe8af - std::sys::pal::unix::thread::Thread::new::thread_start::h086abe36e31ffd04
 140:     0x7f5c72e9bf52 - start_thread
                               at ./nptl/pthread_create.c:447:8
 141:     0x7f5c72f1a678 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
 142:                0x0 - <unknown>


rustc version: 1.85.0-nightly (7c002ff9a 2024-12-25)
platform: x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

**Comment by hermanventer** [comment]
Just FYI: there is no need to add "+nightly-2024-12-26" when running cargo mirai.

As for the crash, it seems likely caused by some change in the Rust compiler or library that did not cause any test suite failures for MIRAI.

I would greatly appreciate it if you could come up with a small test case that reproduces the failure.

If you run mirai with "MIRAI_LOG=info" in your environment, you'll be able to figure out which function causes MIRAI to crash.

**Comment by mbuesch** [comment]
>Just FYI: there is no need to add "+nightly-2024-12-26" when running cargo mirai.

Yeah, well. It will crash with some other "could not find rustc library something" error then.

>I would greatly appreciate it if you could come up with a small test case that reproduces the failure.

I compiled MIRAI with nightly-2024-12-26 and then I ran it on a couple of projects such as https://github.com/mbuesch/letmein

But it failed on other projects, too.
For me it failed for everything, except for trivial empty projects.

**Comment by hermanventer** [comment]
I can't run MIRAI over https://github.com/mbuesch/letmein on my Apple laptop because it does not compile. Is there something much simpler that fails for you? Also, does the MIRAI validation script succeed on your system?

**Comment by mbuesch** [comment]
>on my Apple laptop because it does not compile

Ok. The daemon part is Linux-only.

It also crashes with this other project: https://github.com/mbuesch/feedreaders
This project should compile on Mac.

>Also, does the MIRAI validation script succeed on your system?

How do I check this?

**Comment by davidsemakula** [comment]
I've run into this as well, the issue is caused by ["KnownName" resolution](https://github.com/endorlabs/MIRAI/blob/main/checker/src/known_names.rs#L197)

A simple example reproducer is
```rust
let v = vec![1, 2, 3];
v.remove(1);
```

In general, you need a call to a "KnownName" function that internally (inside its body) declares (and calls) another function (with a different signature), the internal function is then wrongly resolved as a "KnownName" based on it's parent function.

For the above case, [`Vec<T>::remove` calls `ptr::copy`](https://github.com/rust-lang/rust/blob/7a0cde96f83c6d38237bb8062df6300ecf4c2687/library/alloc/src/vec/mod.rs#L2063), which [internally calls `precondition_check` via the `assert_unsafe_precondition!` macro](https://github.com/rust-lang/rust/blob/7a0cde96f83c6d38237bb8062df6300ecf4c2687/library/core/src/intrinsics/mod.rs#L4476). However, this internal call is only added [if debug assertions are enabled and the caller (of `ptr::copy`) is generic"](https://github.com/rust-lang/rust/blob/7a0cde96f83c6d38237bb8062df6300ecf4c2687/library/core/src/ub_checks.rs#L27-L31), so direct call of `ptr::copy` won't reproduce this bug.

I'm working a comprehensive fix for this (i.e. more robust "KnownName" resolution), I should be able to make a PR tomorrow.

**Comment by hermanventer** [comment]
Seems this has been resolved.
